apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker_cust_upl
spec:
  selector:
    matchLabels:
      app: docker_cust_upl
  replicas: 1 
  template: 
    metadata:
      labels:
        app: docker_cust_upl
    spec:
      containers:
      - name: docker_cust_upl
        image: darielhg89/docker_cust_upl:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: docker_cust_upl
spec:
 type: NodePort
 selector:
   app: docker_cust_upl
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: docker_cust_upl
